--------------------------------------------------------
--  File created - Segunda-feira-Dezembro-18-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DATAFILE
--------------------------------------------------------

  CREATE TABLE "MANAGER"."DATAFILE" 
   (	"NAME_DF" VARCHAR2(200 BYTE), 
	"NAME_TB" VARCHAR2(200 BYTE), 
	"FILE_SIZE" NUMBER(8,0), 
	"USED_SIZE" NUMBER(8,0), 
	"STATUS" VARCHAR2(200 BYTE), 
	"TIMESTAMP" NUMBER(20,0), 
	"TIMESTAMP_TB" NUMBER(20,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TP_TABLES" ;
--------------------------------------------------------
--  DDL for Table SESSIONS
--------------------------------------------------------

  CREATE TABLE "MANAGER"."SESSIONS" 
   (	"ID_SESSION" NUMBER(8,0), 
	"STATUS" VARCHAR2(20 BYTE), 
	"SID" NUMBER(8,0), 
	"USER_ID" NUMBER(8,0), 
	"SERIAL" NUMBER(8,0), 
	"TIMESTAMP_SS" NUMBER(20,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TP_TABLES" ;
--------------------------------------------------------
--  DDL for Table SYSTEM
--------------------------------------------------------

  CREATE TABLE "MANAGER"."SYSTEM" 
   (	"TIMESTAMP" NUMBER(20,0), 
	"MEMORY" NUMBER(20,0), 
	"LOAD" NUMBER(20,0), 
	"CPU" NUMBER(20,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TP_TABLES" ;
--------------------------------------------------------
--  DDL for Table TABLESPACE
--------------------------------------------------------



  CREATE TABLE "MANAGER"."TABLESPACE" 
   (
   "NAME" VARCHAR2(200 BYTE),   
	"USED_SIZE" NUMBER(8,0), 
    "FREE_SIZE" NUMBER(8,0),
	"TOTAL_SIZE" NUMBER(8,0),
    "TIME_STAMP" TIMESTAMP(6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 57344)
  TABLESPACE "TP_TABLES" ;
--------------------------------------------------------
--  DDL for Table TABLESPACE_USER
--------------------------------------------------------

  CREATE TABLE "MANAGER"."TABLESPACE_USER" 
   (	"NAME_TB" VARCHAR2(20 BYTE), 
	"ID_USER" NUMBER(8,0), 
	"TIMESTAMP_TB" NUMBER(20,0), 
	"TIMESTAMP_SES" NUMBER(20,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TP_TABLES" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "MANAGER"."USERS" 
   (	"USER_ID" NUMBER(8,0), 
	"USERNAME" VARCHAR2(20 BYTE), 
    "ACCOUNT_STATUS" VARCHAR2(20 BYTE), 
	"DEFAULT_TB" VARCHAR2(20 BYTE), 
	"TEMP_TB" VARCHAR2(20 BYTE), 
	"CREATED" VARCHAR2(20 BYTE), 
	"TIMESTAMP" TIMESTAMP(6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TP_TABLES" ;
REM INSERTING into MANAGER.DATAFILE
SET DEFINE OFF;
REM INSERTING into MANAGER.SESSIONS
SET DEFINE OFF;
REM INSERTING into MANAGER.SYSTEM
SET DEFINE OFF;
REM INSERTING into MANAGER.TABLESPACE
SET DEFINE OFF;
REM INSERTING into MANAGER.TABLESPACE_USER
SET DEFINE OFF;
REM INSERTING into MANAGER.USERS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MANAGER"."USERS_PK" ON "MANAGER"."USERS" ("ID", "TIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TP_TABLES" ;
--------------------------------------------------------
--  DDL for Index SYSTEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MANAGER"."SYSTEM_PK" ON "MANAGER"."SYSTEM" ("TIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "TP_TABLES" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MANAGER"."TABLE1_PK" ON "MANAGER"."DATAFILE" ("NAME_DF", "TIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TP_TABLES" ;
--------------------------------------------------------
--  DDL for Index SESSIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MANAGER"."SESSIONS_PK" ON "MANAGER"."SESSIONS" ("ID_SESSION", "TIMESTAMP_SS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TP_TABLES" ;
--------------------------------------------------------
--  DDL for Index PRIMARY_KEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "MANAGER"."PRIMARY_KEY" ON "MANAGER"."TABLESPACE" ("NAME", "TIME_STAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TP_TABLES" ;
--------------------------------------------------------
--  DDL for Index TABLESPACE_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MANAGER"."TABLESPACE_USER_PK" ON "MANAGER"."TABLESPACE_USER" ("NAME_TB", "ID_USER", "TIMESTAMP_TB", "TIMESTAMP_SES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TP_TABLES" ;
--------------------------------------------------------
--  Constraints for Table TABLESPACE_USER
--------------------------------------------------------

  ALTER TABLE "MANAGER"."TABLESPACE_USER" MODIFY ("TIMESTAMP_TB" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."TABLESPACE_USER" MODIFY ("NAME_TB" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."TABLESPACE_USER" MODIFY ("ID_USER" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."TABLESPACE_USER" MODIFY ("TIMESTAMP_SES" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."TABLESPACE_USER" ADD CONSTRAINT "TABLESPACE_USER_PK" PRIMARY KEY ("NAME_TB", "ID_USER", "TIMESTAMP_TB", "TIMESTAMP_SES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TP_TABLES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DATAFILE
--------------------------------------------------------

  ALTER TABLE "MANAGER"."DATAFILE" MODIFY ("NAME_DF" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."DATAFILE" MODIFY ("NAME_TB" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."DATAFILE" MODIFY ("FILE_SIZE" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."DATAFILE" MODIFY ("USED_SIZE" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."DATAFILE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."DATAFILE" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."DATAFILE" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("NAME_DF", "TIMESTAMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TP_TABLES"  ENABLE;
  ALTER TABLE "MANAGER"."DATAFILE" MODIFY ("TIMESTAMP_TB" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "MANAGER"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."USERS" MODIFY ("DEFAULT_TB" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."USERS" MODIFY ("TEMP_TB" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."USERS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."USERS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."USERS" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID", "TIMESTAMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TP_TABLES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SESSIONS
--------------------------------------------------------

  ALTER TABLE "MANAGER"."SESSIONS" MODIFY ("ID_SESSION" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."SESSIONS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."SESSIONS" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."SESSIONS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."SESSIONS" MODIFY ("SERIAL" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."SESSIONS" MODIFY ("TIMESTAMP_SS" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."SESSIONS" ADD CONSTRAINT "SESSIONS_PK" PRIMARY KEY ("ID_SESSION", "TIMESTAMP_SS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TP_TABLES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TABLESPACE
--------------------------------------------------------

  ALTER TABLE "MANAGER"."TABLESPACE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."TABLESPACE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."TABLESPACE" MODIFY ("TOTAL_SIZE" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."TABLESPACE" MODIFY ("USED_SIZE" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."TABLESPACE" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."TABLESPACE" ADD CONSTRAINT "PRIMARY_KEY" PRIMARY KEY ("NAME", "TIME_STAMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TP_TABLES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SYSTEM
--------------------------------------------------------

  ALTER TABLE "MANAGER"."SYSTEM" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."SYSTEM" MODIFY ("MEMORY" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."SYSTEM" MODIFY ("LOAD" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."SYSTEM" MODIFY ("CPU" NOT NULL ENABLE);
  ALTER TABLE "MANAGER"."SYSTEM" ADD CONSTRAINT "SYSTEM_PK" PRIMARY KEY ("TIMESTAMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "TP_TABLES"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DATAFILE
--------------------------------------------------------

  ALTER TABLE "MANAGER"."DATAFILE" ADD CONSTRAINT "DATAFILE_FK1" FOREIGN KEY ("NAME_DF", "TIMESTAMP_TB")
	  REFERENCES "MANAGER"."TABLESPACE" ("NAME", "TIME_STAMP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SESSIONS
--------------------------------------------------------

  ALTER TABLE "MANAGER"."SESSIONS" ADD CONSTRAINT "SESSIONS_FK1" FOREIGN KEY ("ID_SESSION", "TIMESTAMP_SS")
	  REFERENCES "MANAGER"."USERS" ("ID", "TIMESTAMP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TABLESPACE_USER
--------------------------------------------------------

  ALTER TABLE "MANAGER"."TABLESPACE_USER" ADD CONSTRAINT "TABLESPACE_USER_FK1" FOREIGN KEY ("NAME_TB", "TIMESTAMP_TB")
	  REFERENCES "MANAGER"."TABLESPACE" ("NAME", "TIME_STAMP") ENABLE;
  ALTER TABLE "MANAGER"."TABLESPACE_USER" ADD CONSTRAINT "TABLESPACE_USER_FK2" FOREIGN KEY ("ID_USER", "TIMESTAMP_SES")
	  REFERENCES "MANAGER"."USERS" ("ID", "TIMESTAMP") ENABLE;
