INSERT INTO "MANAGER".SESSIONS
(SID,USER_ID,USERNAME,SERIAL,TIMESTAMP)
select SID, USER#, USERNAME, SERIAL#,c.CURRENT_TIMESTAMP 
    from v$session, (SELECT CURRENT_TIMESTAMP FROM dual) c 
        order by 1; 
    
select * from "MANAGER".SESSIONS ;     